.travis.yml
README.md
app/package.json

Haven't figured out a way to fix the lint-errors yet because I'm not familiar with nodejs/javascript. But I think this seems a good start.

add travis-ci tests to puppetmaster-gui app

---

app/routes/servers.js

Implemented a check that will find out if the current user is root, this check is then used to prepend sudo to commands for non root users.
Fixes issue #2  and obsoletes issue #3

Only sudo when not root

---

app/public/js/atomia.js
app/views/wizard/winrm_warning.jade

It now works with both powershell and cmd. Also added a copy to clipboard button.
Fixes issue #8

Modified the winrm command information 

---

app/lib/puppetdb.js
app/middleware/menu.js
app/public/js/atomia.js
app/routes/servers.js
app/routes/wizard.js
app/views/menu.jade
app/views/servers/add_server.jade
app/views/wizard/winrm_warning.jade

The update hostname button will now update the information in the database when pressed.
Also fixed various bugs related to this functionality.
Fix #9

Now allows modifying the server hostname field

---

app/routes/wizard.js
app/views/wizard/glusterfs.jade

Fix skip button for GlusterFS

---

app/lib/puppetdb.js
app/routes/wizard.js
app/views/wizard/latest_puppet_run.jade

Now shows a warning message in the gui about PuppetDB not running. Will no longer crash the app.
Fix #17

Be more graceful when PuppetDB is not running

---

app/public/js/atomia.js

Replace fqdn with server hostname

---

app/public/js/atomia.js

Increase the strength of generated passwords

---

install.sh

Update install.sh to be usable by non-root user

---

app/routes/servers.js

Change the way winrm command strings were escaped

---

app/layout.hbs
app/platform-options/platform-options.hbs
app/platform-options/requirements.hbs
app/public/css/installer.css
app/public/js/platform-options.js

* Changed css-classes to component-based
* Added font awesome (icons) via CDN for now
* General changes to colors and whitespaces

Updated design of existing views to conform with mockups

---

app/app.js
app/config/environments/live_environment.json
app/config/roles/active_directory.json
app/config/roles/internaldns.json
app/layout.hbs
app/package.json
app/platform-options/model.js
app/platform-options/platform-options.hbs
app/public/js/platform-options.js
app/public/js/servers.js
app/restate-machine/index.js
app/servers/index.js
app/servers/model.js
app/servers/servers.hbs

It is now possible to provision a single machine on EC2 via restate machine

Initial provisioning of servers on EC2

---

app/layout.hbs
app/platform-options/index.js
app/platform-options/model.js
app/platform-options/platform-options.hbs
app/platform-options/requirements.hbs
app/public/css/installer.css
app/public/js/platform-options.js
app/public/js/view_models.js
app/servers/servers.hbs
app/start/start.hbs

Added navigation between the implemented pages
Save platform options changes to the database automatically

Navigating through the pages now works as expected

---

app/layout.hbs
app/lib/puppet_helper.js
app/package.json
app/public/js/knockout-else.js
app/puppet-config/puppet-config.hbs

Display %int_booleans as switches

---

app/lib/puppet_helper.js
app/public/js/servers.js
app/servers/model.js
statemachines/pre_flight_checks/start
statemachines/pre_flight_checks/test_dns
statemachines/pre_flight_checks/test_hostname_resolves
statemachines/pre_flight_checks/test_login
statemachines/pre_flight_checks/test_operating_system
statemachines/pre_flight_checks/test_repo_access
statemachines/pre_flight_checks/test_root
statemachines/pre_flight_checks/test_system_requirements
statemachines/pre_flight_checks/winrm/test_administrator.py
statemachines/pre_flight_checks/winrm/test_dns.py
statemachines/pre_flight_checks/winrm/test_os.py
statemachines/pre_flight_checks/winrm/test_requirements.py
statemachines/pre_flight_checks/winrm/test_winrm.py

Adds a statemachine with the intial sets of pre flight checks

Pre flight checks

---

README.md
app/app.js
app/lib/database_helper.js
app/platform-options/model.js
app/pre-flight/index.js
app/pre-flight/model.js
app/schema.sql
app/servers/index.js
app/servers/model.js

Database improvements
Added database schema

New installer

---

app/config/environments/live_environment.json
app/config/roles/config.json
app/config/roles/configuration.json
app/config/roles/windows_base.json
app/installation/index.js
app/installation/installation.hbs
app/installation/model.js
app/platform-options/model.js
app/pre-flight/model.js
app/pre-flight/pre-flight.hbs
app/public/js/installation.js
app/public/js/pre-flight.js
app/public/js/puppet-config.js
app/public/js/servers.js
app/public/js/view_models.js
app/puppet-config/index.js
app/puppet-config/model.js
app/puppet-config/puppet-config.hbs
app/servers/index.js
app/servers/model.js
app/servers/servers.hbs
statemachines/provision_server/scripts/install_puppet.sh
statemachines/provision_server/setup_puppet
statemachines/provision_server/winrm/run_puppet.py

Pretty much, all tweaking of the puppet manifests from here on

Alot of different improvements, all steps can now be completed

---

install.sh

It's pointless to have puppet running without FQDN. Plus database name is fixed. :)

sql query database name correction

---

app/views/menu.jade

Will be replaced with dashboard functionality later.

Removed the sidebar due to buggy interaction

---

app/app.js
app/bin/www
app/middleware/menu.js
app/npm-shrinkwrap.json
app/package.json
app/routes/config.js
app/routes/servers.js
app/routes/wizard.js
typings/node/node.d.ts

Replaced deprecated and removed unused packages.
Resolves PROD-1573
ChangeLog:
[UPDATE] - Updated packages version

Update and replace deprecated packages

---

install-rhel7.sh

Added script that allows installation of puppet on CentOS 7.
Partially resolves PROD-1931.

Add CentOS 7 install script
